# Generated by Django 3.2.9 on 2021-12-04 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Urls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField(max_length=2000)),
                ('shortened_url', models.URLField(blank=True, null=True)),
                ('short_char', models.CharField(blank=True, max_length=6, null=True)),
            ],
        ),
    ]
